name: CI

on:
  pull_request:
    branches: [master]
    types: [synchronize]

jobs:
  CI:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "zulu"
      - uses: sbt/setup-sbt@v1          
      - name: compile
        run: sbt compile
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
